export const mySkills = [
  { title: "HTML", icon: "html" },
  { title: "CSS", icon: "css" },
  { title: "JavaScript", icon: "javascript" },
  { title: "TypeScript", icon: "typescript" },
  { title: "ReactJS", icon: "react" },
  { title: "NextJS", icon: "nextjs" },
  { title: "Tailwind CSS", icon: "tailwind" },
  { title: "shadcn/ui", icon: "shadcn" },
  { title: "NodeJS", icon: "nodejs" },
  { title: "ExpressJS", icon: "express" },
  { title: "MongoDB", icon: "mongodb" },
  { title: "Git", icon: "git" },
  { title: "GitHub", icon: "gitHub" },
  { title: "Vercel", icon: "vercel" },
  { title: "Postman", icon: "postman" },
  { title: "Docker", icon: "docker" },
  { title: "Radix UI", icon: "radix" },
];
